/**
 * Mock product data — matches images folder naming convention
 * In production, these come from Supabase via backend API
 */
export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: 'Ram Mandir Illuminated Wall Frame',
    slug: 'illuminated-wall-frame',
    price: 2499,
    originalPrice: 3299,
    category: 'Wall Decor',
    rating: 4.9,
    reviewCount: 128,
    description: 'A beautifully illuminated wall frame depicting the Ram Mandir, crafted with LED lighting and premium wood frame. Perfect centerpiece for your puja room or living area.',
    features: ['LED illuminated', 'Premium wood frame', 'Easy installation', 'Suitable for indoors'],
    image: '/images/products/illuminated-wall-frame.png',
    stock: 45,
    badge: 'Bestseller',
  },
  {
    id: 2,
    name: 'Om Mandala LED Wall Art',
    slug: 'led-wall-art',
    price: 3850,
    originalPrice: 4999,
    category: 'Wall Decor',
    rating: 4.8,
    reviewCount: 96,
    description: 'Intricate mandala design featuring the sacred Om symbol with warm LED backlighting. A stunning addition to meditation spaces and living rooms.',
    features: ['Handcrafted mandala', 'Warm LED glow', 'USB powered', 'Multiple sizes'],
    image: '/images/products/led-wall-art.png',
    stock: 30,
    badge: 'New Arrival',
  },
  {
    id: 3,
    name: 'Metropolitan Street Canvas Painting',
    slug: 'canvas-painting',
    price: 12500,
    originalPrice: 15000,
    category: 'Canvas Art',
    rating: 4.7,
    reviewCount: 54,
    description: 'A bold, contemporary canvas painting capturing the vibrant energy of Indian metropolitan streets. Gallery-quality print on premium stretched canvas.',
    features: ['Gallery canvas', 'UV resistant inks', 'Ready to hang', 'Certificate of authenticity'],
    image: '/images/products/canvas-painting.png',
    stock: 12,
    badge: 'Limited Edition',
  },
  {
    id: 4,
    name: 'Emerald Falls Nature Canvas',
    slug: 'emerald-falls-canvas',
    price: 4200,
    originalPrice: 5500,
    category: 'Canvas Art',
    rating: 4.9,
    reviewCount: 78,
    description: 'Serene emerald waterfall captured in vivid detail on premium canvas. Brings the calm of nature into your living space.',
    features: ['High-resolution print', 'Stretched canvas', 'Eco-friendly inks', 'Multiple sizes'],
    image: '/images/products/emerald-falls-canvas.png',
    stock: 25,
    badge: 'Top Rated',
  },
  {
    id: 5,
    name: 'Ivory Marble Twist Vase',
    slug: 'ivory-marble-vase',
    price: 3200,
    originalPrice: 4200,
    category: 'Vases',
    rating: 4.8,
    reviewCount: 62,
    description: 'Elegantly twisted ivory-white marble vase. A sculptural piece that stands beautifully on its own or paired with dried botanicals.',
    features: ['Natural marble', 'Handcrafted', 'Stable base', 'Easy to clean'],
    image: '/images/products/ivory-marble-vase.png',
    stock: 18,
    badge: 'Popular',
  },
  {
    id: 6,
    name: 'Stone Mosaic Designer Vase',
    slug: 'stone-mosaic-vase',
    price: 2800,
    originalPrice: 3600,
    category: 'Vases',
    rating: 4.7,
    reviewCount: 41,
    description: 'Artisan-crafted vase with intricate stone mosaic pattern. Each piece is unique — no two are exactly alike.',
    features: ['Mosaic inlay', 'Waterproof interior', 'Artisan made', 'Unique pattern'],
    image: '/images/products/stone-mosaic-vase.png',
    stock: 20,
    badge: null,
  },
  {
    id: 7,
    name: 'Amber Swirl Glass Vase',
    slug: 'amber-swirl-vase',
    price: 1999,
    originalPrice: 2800,
    category: 'Vases',
    rating: 4.6,
    reviewCount: 89,
    description: 'Hand-blown amber glass vase with mesmerizing swirl pattern. Catches light beautifully on windowsills and shelves.',
    features: ['Hand-blown glass', 'Amber colour', 'Heat resistant', 'Dishwasher safe'],
    image: '/images/products/amber-swirl-vase.png',
    stock: 35,
    badge: null,
  },
  {
    id: 13,
    name: 'Floral Glow Table Lamp',
    slug: 'floral-glow-table-lamp',
    price: 4500,
    originalPrice: 5999,
    category: 'Lighting',
    rating: 4.8,
    reviewCount: 42,
    description: 'Exquisite table lamp with a hand-painted floral design that glows softly when lit. Adds a touch of vintage elegance to any room.',
    features: ['Hand-painted ceramic', 'Fabric shade', 'Adjustable brightness', 'Energy efficient LED'],
    image: '/images/products/floral-glow-table-lamp.png',
    stock: 15,
    badge: 'Artisan Pick',
  },
  {
    id: 14,
    name: 'Halo Crystal Ring Lamp',
    slug: 'halo-crystal-ring-lamp',
    price: 18500,
    originalPrice: 22000,
    category: 'Lighting',
    rating: 5.0,
    reviewCount: 18,
    description: 'Modern halo ring lamp embedded with premium K9 crystals for a brilliant light refraction effect. A true statement piece for luxury interiors.',
    features: ['Premium K9 crystals', 'Dimmable LED', 'Stainless steel body', 'Remote controlled'],
    image: '/images/products/halo-crystal-ring-lamp.png',
    stock: 8,
    badge: 'Luxury',
  },
  {
    id: 15,
    name: 'Royal Crystal Tassel Pendant Lamp',
    slug: 'royal-crystal-tassel-pendant-lamp',
    price: 24000,
    originalPrice: 28500,
    category: 'Lighting',
    rating: 4.9,
    reviewCount: 12,
    description: 'Grand pendant lamp featuring layers of crystal tassels and brass accents. Inspired by royal Indian palaces.',
    features: ['Royal design', 'Brass finish', 'Multi-tier crystals', 'Installation included'],
    image: '/images/products/royal-crystal-tassel-pendant-lamp.png',
    stock: 5,
    badge: 'Royal Heritage',
  },
  {
    id: 16,
    name: 'Ruby Crystal Fringe Pendant Lamp',
    slug: 'ruby-crystal-fringe-pendant-lamp',
    price: 21500,
    originalPrice: 25000,
    category: 'Lighting',
    rating: 4.8,
    reviewCount: 24,
    description: 'Stunning pendant lamp with ruby-tinted crystal fringes that create a warm, romantic glow.',
    features: ['Ruby tinted glass', 'Crystal fringe', 'Unique aesthetic', 'Adjustable height'],
    image: '/images/products/ruby-crystal-fringe-pendant-lamp.png',
    stock: 10,
    badge: null,
  },
  {
    id: 17,
    name: 'Turquoise Crown Crystal Pendant Lamp',
    slug: 'turquoise-crown-crystal-pendant-lamp',
    price: 19500,
    originalPrice: 23000,
    category: 'Lighting',
    rating: 4.7,
    reviewCount: 15,
    description: 'Elegant crown-shaped pendant lamp with turquoise accents and clear crystals. Perfect for dining areas.',
    features: ['Turquoise accents', 'Crown shape', 'Clear crystals', 'Statement lighting'],
    image: '/images/products/turquoise-crown-crystal-pendant-lamp.png',
    stock: 7,
    badge: null,
  },
  {
    id: 18,
    name: 'Vintage Gear Wall Clock',
    slug: 'vintage-gear-wall-clock',
    price: 3200,
    originalPrice: 4500,
    category: 'Wall Decor',
    rating: 4.6,
    reviewCount: 38,
    description: 'Industrial vintage wall clock with exposed moving gears. A unique blend of mechanical art and timepiece.',
    features: ['Moving gears', 'Silent mechanism', 'Metal construction', '24 inch diameter'],
    image: '/images/products/vintage-gear-wall-clock.png',
    stock: 20,
    badge: 'Vintage Style',
  },
  {
    id: 19,
    name: 'Zen Aura Lamp',
    slug: 'zen-aura-lamp',
    price: 5800,
    originalPrice: 7500,
    category: 'Lighting',
    rating: 4.9,
    reviewCount: 56,
    description: 'Minimalist ambient lamp designed to create a Zen-like atmosphere. Features warm wooden elements and a soft parchment diffuser.',
    features: ['Minimalist design', 'Natural wood', 'Soft diffusion', 'Perfect for meditation'],
    image: '/images/products/zen-aura-lamp.png',
    stock: 25,
    badge: 'Zen Living',
  },
]

export const CATEGORIES = ['All', 'Wall Decor', 'Canvas Art', 'Vases', 'Lighting']

/** Format price to Indian Rupee notation */
export const formatPrice = (price) => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price)
}

/** Calculate discount percentage */
export const getDiscount = (price, originalPrice) => {
  if (!originalPrice || originalPrice <= price) return null
  return Math.round(((originalPrice - price) / originalPrice) * 100)
}

/** API base URL from environment */
export const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000'
